### ISSUE TITLE
KeyError: '_module' 

### ISSUE THREAD

**Issue by lowk3y** [nccgroup/G-Scout#12]
I am having issues starting the G-Scout audit

```
(venv) a@zbox:~/src/G-Scout$ python gscout.py -p-name "XXXXX" 
Traceback (most recent call last):
  File "gscout.py", line 115, in <module>
    main()
  File "gscout.py", line 97, in main
    list_projects(project_or_org='project-name', specifier=args.project_name)
  File "gscout.py", line 36, in list_projects
    'v1', credentials=storage.get())
  File "/home/a/src/G-Scout/venv/local/lib/python2.7/site-packages/oauth2client/client.py", line 407, in get
    return self.locked_get()
  File "/home/a/src/G-Scout/venv/local/lib/python2.7/site-packages/oauth2client/file.py", line 54, in locked_get
    credentials = client.Credentials.new_from_json(content)
  File "/home/a/src/G-Scout/venv/local/lib/python2.7/site-packages/oauth2client/client.py", line 302, in new_from_json
    module_name = data['_module']
KeyError: '_module'
```

**Comment by angelomellos** [comment]
Hello,
I'm not sure what causes this error. I do know someone else has gotten this and it was fixed after just starting over from scratch. Sorry that's the best I've got.
